version: '2.0'

services:
  brewer-api-web:
    container_name: brewer-api-web
    build:
      context: ./docker/nginx
    ports:
      - "8030:80"
    volumes:
      - ./public:/appdata/www/public
    depends_on:
      - brewer-api-php
    networks:
      - brewer-api-network

  brewer-api-php:
    container_name: brewer-api-php
    build:
      context: docker/php
    volumes:
      - ./:/appdata/www
    depends_on:
      - brewer-api-db
    networks:
      - brewer-api-network


  brewer-api-db:
    container_name: brewer-api-db
    image: mysql:8.0
    build:
      context: ./docker/database
    ports:
      - 36000:3306
    environment:
      MYSQL_DATABASE: brewer_db
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      -  brewer-api-db-data:/var/lib/mysql
    networks:
      - brewer-api-network

volumes:
  brewer-api-db-data:

networks:
  brewer-api-network: