parameters:
    punk.api.base.uri: '%env(PUNK_API_BASE_URI)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $punkApiBaseUri: "%punk.api.base.uri%"

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Beer/Domain/Entity/'
            - '../src/Kernel.php'
    
    App\Http\:
        resource: '../src/Http'
        tags: ['controller.service_arguments']
    
    App\Shared\Infrastructure\PunkApiClient: ~
    App\Beer\Infrastructure\Repository\HttpServiceInterface: '@App\Shared\Infrastructure\PunkApiClient'


    App\JsonExceptionResponseTransformerListener:
        tags: 
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100}


