framework:
    test: true
    
services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Apps\:
        resource: '../tests/Apps/*'
        
    App\Beer\Infrastructure\HttpServiceInterface:
        public: true
    
    App\Beer\Application\FindBeer:
        public: true
    
    App\Beer\Application\FindBeerForFood:
        public: true

    
